import Image from "next/image";
import { Bottle } from "./Bottle";
import type { Formula } from "@/lib/products";

type Props = {
  formula: Formula;
  size?: number;
  className?: string;
  priority?: boolean;
  detailed?: boolean;
};

/**
 * Real photo when `formula.photo` is set, SVG bottle otherwise.
 * Photos live in /public/fotos/opt/{photo}-{240|480|800}.webp generated by
 * scripts/optimize-photos.mjs.
 */
export function BottleImage({ formula, size = 200, className, priority, detailed }: Props) {
  if (!formula.photo) {
    return <Bottle formula={formula} size={size} className={className} detailed={detailed} />;
  }

  const w = size;
  const h = Math.round(size * 1.8);

  return (
    <div
      className={`relative ${className ?? ""}`}
      style={{ width: w, height: h }}
    >
      <Image
        src={`/fotos/opt/${formula.photo}-480.webp`}
        alt={`Frasco ${formula.name}`}
        fill
        sizes={`${size}px`}
        priority={priority}
        className="object-contain"
      />
    </div>
  );
}
